paths:
  /api/products:
    get:
      summary: Obtiene todos los productos
      tags:
        - Products
      responses:
        "201":
          description: Los productos fueron obtentidos satisfactoriamente de la base de datos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo de conexión con la base de datos
    post:
      summary: Crear un producto
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/createProduct"
      responses:
        "201":
          description: Producto creado correctamante
        "500":
          description: Error al crear el producto
  /api/products/{pid}:
    get:
      summary: Obtiene un producto a partir de su Id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: El id del producto que desea solicitar
          schema:
            $type: String
      responses:
        "201":
          description: El producto fue obtenido correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo de conexión con la base de datos
    put:
      summary: Actualiza un producto a partir de su id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: El id del producto que se desea actualizar {66523418f9c6848e3d48e8dc}
          schema:
            $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/requestBodies/updateProduct"
      responses:
        "201":
          description: Producto actualziado correctamante
        "500":
          description: Error al actualizar el producto
    delete:
      summary: Eliminar un producto a partir de su Id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: El id del producto que desea eliminar
          schema:
            $type: String
      responses:
        "201":
          description: El producto fue eliminado correctamente
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "500":
          description: Error interno del servidor, usualmente generado por una query defectuosa o un fallo de conexión con la base de datos
  /api/products/disable/{pid}:
    put:
      summary: Deshabilita un producto a partir de su id
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: El id del producto que se desea deshabilitar
          schema:
            $type: String
      responses:
        "201":
          description: Producto deshabilitado correctamante
        "500":
          description: Error al deshabilitar el producto
components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerado de mongo
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripción del producto
        code:
          type: String
          description: Código del producto
        price:
          type: Number
          description: Precio del producto
        status:
          type: Boolean
          description: Bandera para saber si el producto está abilitado
        stock:
          type: Number
          description: Cantidad de productos en el stock
        category:
          type: String
          description: Categoría del producto
        thumbnail:
          type: Array
          description: Arreglo de imágenes del producto
        owner:
          type: String
          description: El correo electrónico del vendedor del producto
      example:
        _id: ObjectId("66523418f9c6848e3d48e8dc")
        title: Cinta métrica
        description: Cinta métrica 5 metros
        code: CM123456
        price: 15
        status: true
        stock: 3
        category: Medición
        thumbnail: ["/public/images/imagen1.jpg", "/public/images/imagen2.jpg"]
        owner: test@api.com
  requestBodies:
    updateProduct:
      type: object
      properties:
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripción del producto
        code:
          type: String
          description: Código del producto
        price:
          type: Number
          description: Precio del producto
        status:
          type: Boolean
          description: Bandera para saber si el producto está abilitado
        stock:
          type: Number
          description: Cantidad de productos en el stock
        category:
          type: String
          description: Categoría del producto
        thumbnail:
          type: Array
          description: Arreglo de imágenes del producto
        owner:
          type: String
          description: El correo electrónico del vendedor del producto
      example:
        title: Cinta métrica
        description: Cinta métrica 5 metros
        code: CM123456
        price: 15
        status: true
        stock: 3
        category: Medición
        thumbnail: ["/public/images/imagen1.jpg", "/public/images/imagen2.jpg"]
        owner: test@api.com
    createProduct:
      type: object
      properties:
        title:
          type: String
          description: Nombre del producto
        description:
          type: String
          description: Descripción del producto
        code:
          type: String
          description: Código del producto
        price:
          type: Number
          description: Precio del producto
        status:
          type: Boolean
          description: Bandera para saber si el producto está abilitado
        stock:
          type: Number
          description: Cantidad de productos en el stock
        category:
          type: String
          description: Categoría del producto
        thumbnail:
          type: Array
          description: Arreglo de imágenes del producto
        owner:
          type: String
          description: El correo electrónico del vendedor del producto
      example:
        title: Navaja Victorinox
        description: Navaja Victorinox con 5 accesorios
        code: NV123456
        price: 1500
        status: true
        stock: 5
        category: Navaja
        thumbnail: ["/public/images/imagen1.jpg", "/public/images/imagen2.jpg"]
        owner: test@api.com
